// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PSM.Core.Core.Database;

#nullable disable

namespace PSM.Core.Migrations
{
    [DbContext(typeof(PermissionContext))]
    partial class PermissionContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PSM.Core.Core.Database.Tables.GlobalPermissionSet", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<string>("PermissionString")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("UserID");

                    b.ToTable("PermissionGlobal");
                });

            modelBuilder.Entity("PSM.Core.Core.Database.Tables.InstancePermissionSet", b =>
                {
                    b.Property<int>("UserID")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("InstanceID")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<string>("PermissionString")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("UserID", "InstanceID");

                    b.ToTable("PermissionInstance");
                });
#pragma warning restore 612, 618
        }
    }
}
