#[global]
AllowedHosts = "*"

[Logging.LogLevel]
Default = "Information"
[Logging.LogLevel.Microsoft]
AspNetCore = "Warning"

[Database]
Database = "psm_db"
Username = "psmuser"
Password = "pass"
Address = "localhost"
Port = 3306